name: Hourly cron

on:
  schedule:
    - cron: "0 * * * *"  # kas valandą
  workflow_dispatch:      # leidžia paleisti rankiniu būdu

jobs:
  hourly-task:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      # TODO: Įdėkite savo komandą/skriptą čia.
      # - name: Run task
      #   run: |
      #     echo "Hello from hourly cron"
